### ISSUE TITLE
KeyError u'DingDing'

### ISSUE THREAD

**Issue by shiyongjason** [1018ji/sentry_dingtalk_xz#3]
![image](https://user-images.githubusercontent.com/22488321/88496963-619d7b00-cff1-11ea-95dd-1f29bfb91a94.png)
作者能不能帮忙看下

**Comment by 1018ji** [comment]
你用的啥版本，我可以给你测试下

**Comment by shiyongjason** [comment]
我已经重新升级版本 已经可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "HouYang"<notifications@github.com&gt;; 
发送时间: 2020年8月4日(星期二) 下午3:21
收件人: "1018ji/sentry_dingtalk_xz"<sentry_dingtalk_xz@noreply.github.com&gt;; 
抄送: "つ怀揣少年梦~"<422703012@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [1018ji/sentry_dingtalk_xz] KeyError u&#39;DingDing&#39; (#3)





 
你用的啥版本，我可以给你测试下

**Comment by 1018ji** [comment]
老版本多少，我尝试坐下兼容，手动鞠躬

**Comment by shiyongjason** [comment]
上次我们运维搞的&nbsp;sentryV9.1.2&nbsp; &nbsp;python2.7 ，之后升级到了&nbsp;Sentry&nbsp;20.8.0.dev0




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "HouYang"<notifications@github.com&gt;; 
发送时间: 2020年8月4日(星期二) 下午3:47
收件人: "1018ji/sentry_dingtalk_xz"<sentry_dingtalk_xz@noreply.github.com&gt;; 
抄送: "つ怀揣少年梦~"<422703012@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [1018ji/sentry_dingtalk_xz] KeyError u&#39;DingDing&#39; (#3)





 
老版本多少，我尝试坐下兼容，手动鞠躬

**Comment by 1018ji** [comment]
好的，我测试下

**Comment by mdreamfly** [comment]
20.8.0.dev0 同样出现了问题

**Comment by shiyongjason** [comment]
https://github.com/FeSeason/sentry-10-dingding
我最后选了这个的 可以参考看下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mdreamfly"<notifications@github.com&gt;; 
发送时间: 2020年8月7日(星期五) 下午2:48
收件人: "1018ji/sentry_dingtalk_xz"<sentry_dingtalk_xz@noreply.github.com&gt;; 
抄送: "つ怀揣少年梦~"<422703012@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [1018ji/sentry_dingtalk_xz] KeyError u&#39;DingDing&#39; (#3)





 
20.8.0.dev0 同样出现了问题

**Comment by mdreamfly** [comment]
> https://github.com/FeSeason/sentry-10-dingding 我最后选了这个的 可以参考看下
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mdreamfly"<notifications@github.com&gt;; 发送时间: 2020年8月7日(星期五) 下午2:48 收件人: "1018ji/sentry_dingtalk_xz"<sentry_dingtalk_xz@noreply.github.com&gt;; 抄送: "つ怀揣少年梦~"<422703012@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [1018ji/sentry_dingtalk_xz] KeyError u&#39;DingDing&#39; (#3) 20.8.0.dev0 同样出现了问题 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的 谢谢 我试试

**Comment by 1018ji** [comment]
@shiyongjason 我添加 sentry_dingtalk_xz 插件在 mac 使用 Sentry On-Premise 部署 releases/9.1.x（目前为 9.1.2）测试无异常，具体你是啥问题我暂时无法复现

**Comment by shiyongjason** [comment]
好的 感谢我到时候再试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "HouYang"<notifications@github.com&gt;; 
发送时间: 2020年8月8日(星期六) 中午11:55
收件人: "1018ji/sentry_dingtalk_xz"<sentry_dingtalk_xz@noreply.github.com&gt;; 
抄送: "つ怀揣少年梦~"<422703012@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [1018ji/sentry_dingtalk_xz] KeyError u&#39;DingDing&#39; (#3)





 
@shiyongjason 我添加 sentry_dingtalk_xz 插件在 mac 使用 Sentry On-Premise 部署 releases/9.1.x（目前为 9.1.2）测试无异常，具体你是啥问题我暂时无法复现

**Comment by 1018ji** [comment]
@mdreamfly 部署不建议使用 dev 部署，我可能无法复现出你们的问题，可以自己整个代码自己改一下即可，手动鞠躬

我这玩意可能测试不全，手动鞠躬

**Comment by 1018ji** [comment]
此问题终结，如果此插件不行，可以换别的尝试，或者反馈问题，感谢各位
